### ISSUE TITLE
Deploy to Azure button not working

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [microsoft/WingtipTicketsSaaS-MultiTenantDB#14]
Please reference the file from the repo instead of blob storage

It shows error on portal.azure.com that 
"There was an error loading the template from URI 'https://wingtipsaas1.blob.core.windows.net/templates-mt/wtpapp.json'. Ensure that the template is publicly accessible and does not have any comments."

**Comment by KalyanChanumolu-MSFT** [comment]
Azure Docs issue [#42077](https://github.com/MicrosoftDocs/azure-docs/issues/42077)

**Comment by Defkon1** [comment]
subscribed to the thread... any workaround while we wait for a fix?

thanks in advance

**Comment by MightyPen** [comment]
Instead of this obscure repo, see this same Issue in.......

- `https://github.com/MicrosoftDocs/azure-docs/issues/42247`

cc: @KalyanChanumolu-MSFT @Defkon1

**Comment by Defkon1** [comment]
any news?

thanks in advance

**Comment by KalyanChanumolu-MSFT** [comment]
I have reached out internally.
I will update when I hear back.

**Comment by KalyanChanumolu-MSFT** [comment]
@MightyPen @Defkon1 The issue is fixed now.
You should be able to publish without any issues

**Comment by MightyPen** [comment]
#please-close

**Comment by Defkon1** [comment]
I can confirm it works like a charm... thanks!
